"""Audit-ready PDF report generation using ReportLab — PostgreSQL backend."""
import os
import json
from datetime import datetime
from reportlab.lib.pagesizes import letter
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib.colors import HexColor
from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle
from reportlab.lib.units import inch

from app.config import REPORTS_DIR
from app.db import get_connection, release_connection


def _fetchone(conn, sql, params=None):
    with conn.cursor(cursor_factory=None) as cur:
        cur.execute(sql, params or [])
        row = cur.fetchone()
        return dict(row) if row else None


def _fetchall(conn, sql, params=None):
    with conn.cursor(cursor_factory=None) as cur:
        cur.execute(sql, params or [])
        return [dict(r) for r in cur.fetchall()]


def _execute(conn, sql, params=None):
    with conn.cursor() as cur:
        cur.execute(sql, params or [])
    conn.commit()


def generate_alert_report(alert_id):
    """Generate a detailed PDF report for a specific alert."""
    conn = get_connection()
    try:
        alert = _fetchone(conn, "SELECT * FROM alerts WHERE id = %s", [alert_id])
    finally:
        release_connection(conn)

    if not alert:
        return None

    filename = f"alert_report_{alert_id}_{datetime.now().strftime('%Y%m%d_%H%M%S')}.pdf"
    filepath = os.path.join(REPORTS_DIR, filename)

    doc = SimpleDocTemplate(filepath, pagesize=letter)
    styles = getSampleStyleSheet()

    title_style = ParagraphStyle('Title', parent=styles['Title'], fontSize=16,
                                  textColor=HexColor('#1a237e'))
    heading_style = ParagraphStyle('H2', parent=styles['Heading2'], fontSize=12,
                                    textColor=HexColor('#283593'))
    body_style = ParagraphStyle('Body', parent=styles['Normal'], fontSize=9, leading=12)

    elements = []

    # Header
    elements.append(Paragraph("COMPLIANCE ALERT REPORT", title_style))
    elements.append(Paragraph(f"Alert ID: {alert_id} | Generated: {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}", body_style))
    elements.append(Spacer(1, 12))

    # Summary table
    data = [
        ['Field', 'Value'],
        ['Account', alert.get('account_id', 'N/A')],
        ['Severity', str(alert.get('severity', 'N/A')).upper()],
        ['Fusion Score', f"{alert.get('fusion_score', 0):.4f}"],
        ['Rule Score', f"{alert.get('rule_score', 0):.4f}"],
        ['ML Score', f"{alert.get('ml_score', 0):.4f}"],
        ['Graph Score', f"{alert.get('graph_score', 0):.4f}"],
        ['Status', alert.get('status', 'pending')],
        ['Created', str(alert.get('created_at', ''))],
    ]
    table = Table(data, colWidths=[1.5*inch, 4*inch])
    table.setStyle(TableStyle([
        ('BACKGROUND', (0, 0), (-1, 0), HexColor('#283593')),
        ('TEXTCOLOR', (0, 0), (-1, 0), HexColor('#ffffff')),
        ('FONTSIZE', (0, 0), (-1, -1), 9),
        ('GRID', (0, 0), (-1, -1), 0.5, HexColor('#cccccc')),
        ('ROWBACKGROUNDS', (0, 1), (-1, -1), [HexColor('#f5f5f5'), HexColor('#ffffff')]),
    ]))
    elements.append(table)
    elements.append(Spacer(1, 15))

    # Triggered rules
    rules = json.loads(alert.get('triggered_rules') or '[]')
    if rules:
        elements.append(Paragraph("TRIGGERED RULES", heading_style))
        for rule_id in rules:
            elements.append(Paragraph(f"• {rule_id}", body_style))
        elements.append(Spacer(1, 10))

    # Explanation
    explanation = json.loads(alert.get('explanation') or '{}')
    if explanation:
        elements.append(Paragraph("DETAILED EXPLANATION", heading_style))
        for key, value in explanation.items():
            if isinstance(value, (list, dict)):
                elements.append(Paragraph(f"<b>{key}</b>: {json.dumps(value, indent=2, default=str)[:500]}", body_style))
            else:
                elements.append(Paragraph(f"<b>{key}</b>: {value}", body_style))
        elements.append(Spacer(1, 10))

    # Review history
    if alert.get('review_action'):
        elements.append(Paragraph("REVIEW HISTORY", heading_style))
        elements.append(Paragraph(f"Action: {alert.get('review_action')}", body_style))
        elements.append(Paragraph(f"Reviewed by: {alert.get('reviewed_by', 'N/A')}", body_style))
        elements.append(Paragraph(f"Reviewed at: {alert.get('reviewed_at', 'N/A')}", body_style))
        if alert.get('review_notes'):
            elements.append(Paragraph(f"Notes: {alert.get('review_notes')}", body_style))

    # Footer
    elements.append(Spacer(1, 30))
    elements.append(Paragraph("This report is auto-generated by the Compliance Agent. "
                               "For questions, contact the compliance team.", body_style))

    doc.build(elements)

    # Save record to DB (separate connection after PDF build succeeds)
    conn = get_connection()
    try:
        _execute(conn, """
            INSERT INTO audit_reports (report_type, filename, alert_ids, summary)
            VALUES (%s, %s, %s, %s)
        """, ('alert_detail', filename, json.dumps([alert_id]),
              f"Alert report for account {alert.get('account_id')}"))
    finally:
        release_connection(conn)

    return filepath


def generate_summary_report():
    """Generate an executive summary PDF of current compliance status."""
    conn = get_connection()
    try:
        def cnt(sql):
            return (_fetchone(conn, sql) or {}).get('cnt', 0)

        stats = {
            'total_alerts': cnt("SELECT COUNT(*) as cnt FROM alerts"),
            'pending':      cnt("SELECT COUNT(*) as cnt FROM alerts WHERE status='pending'"),
            'confirmed':    cnt("SELECT COUNT(*) as cnt FROM alerts WHERE review_action='confirm'"),
            'dismissed':    cnt("SELECT COUNT(*) as cnt FROM alerts WHERE review_action='dismiss'"),
        }

        severity_rows = _fetchall(conn,
            "SELECT severity, COUNT(*) as cnt FROM alerts GROUP BY severity ORDER BY cnt DESC")
        stats['by_severity'] = {r['severity']: r['cnt'] for r in severity_rows}
    finally:
        release_connection(conn)

    filename = f"executive_summary_{datetime.now().strftime('%Y%m%d_%H%M%S')}.pdf"
    filepath = os.path.join(REPORTS_DIR, filename)
    doc = SimpleDocTemplate(filepath, pagesize=letter)
    styles = getSampleStyleSheet()

    title_style = ParagraphStyle('Title', parent=styles['Title'], fontSize=16,
                                  textColor=HexColor('#1a237e'))
    heading_style = ParagraphStyle('H2', parent=styles['Heading2'], fontSize=12,
                                    textColor=HexColor('#283593'))
    body_style = ParagraphStyle('Body', parent=styles['Normal'], fontSize=10, leading=13)

    elements = []
    elements.append(Paragraph("EXECUTIVE COMPLIANCE SUMMARY", title_style))
    elements.append(Paragraph(f"Generated: {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}", body_style))
    elements.append(Spacer(1, 15))

    data = [
        ['Metric', 'Value'],
        ['Total Alerts', str(stats['total_alerts'])],
        ['Pending Review', str(stats['pending'])],
        ['Confirmed', str(stats['confirmed'])],
        ['Dismissed', str(stats['dismissed'])],
    ]
    for sev, c in stats.get('by_severity', {}).items():
        data.append([f'{str(sev).capitalize()} Severity', str(c)])

    table = Table(data, colWidths=[2.5*inch, 2*inch])
    table.setStyle(TableStyle([
        ('BACKGROUND', (0, 0), (-1, 0), HexColor('#283593')),
        ('TEXTCOLOR', (0, 0), (-1, 0), HexColor('#ffffff')),
        ('FONTSIZE', (0, 0), (-1, -1), 10),
        ('GRID', (0, 0), (-1, -1), 0.5, HexColor('#cccccc')),
    ]))
    elements.append(table)
    elements.append(Spacer(1, 20))

    elements.append(Paragraph("This is an automated compliance summary. All pending alerts "
                               "require human review within the SLA defined in the AML policy.", body_style))

    doc.build(elements)

    # Save record to DB
    conn = get_connection()
    try:
        _execute(conn, """
            INSERT INTO audit_reports (report_type, filename, summary)
            VALUES (%s, %s, %s)
        """, ('executive_summary', filename, f"Summary: {stats['total_alerts']} alerts"))
    finally:
        release_connection(conn)

    return filepath
